apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}-vs
spec:
  hosts:
  - {{ .Values.ingress.host }}
  gateways:
  - {{ .Chart.Name }}-gw
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: {{ .Values.service.port }}
        host: {{ .Chart.Name }}-svc