autoscaling:
  enabled: false
replicaCount: 1
podAnnotations:
  notifications.argoproj.io/subscribe.on-sync-succeeded.slack: my-channel1
imagePullSecrets:
  - name: regcred
image:
  repository: fancyit/app-b
  tag: v1
  pullPolicy: Always
service:
  port: 8080
  type: ClusterIP
containers:
  env:
    - name: SERVER_PORT
      value: "8080"
    - name: SERVICE_A_URL
      value: "http://app-a-svc.app-a.svc.cluster.local:8080"
ingress:
  host: "app-b.anban.fun"
external_service:
  url: http://app-a-svc.app-a.svc.cluster.local
  port: 8080